# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stats', jsonfield.fields.JSONField()),
                ('blurb', models.CharField(max_length=2000)),
                ('lore', models.CharField(max_length=4500)),
                ('tags', jsonfield.fields.JSONField()),
                ('allytips', jsonfield.fields.JSONField()),
                ('enemytips', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('sprite', models.CharField(max_length=50)),
                ('h', models.IntegerField()),
                ('w', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='league.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('timestamp', models.BigIntegerField()),
                ('matchId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('queue', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=25)),
                ('platformId', models.CharField(max_length=10)),
                ('lane', models.CharField(choices=[('MID', 'Middle'), ('TOP', 'Top'), ('BOT', 'Marksman'), ('SUP', 'Support'), ('JNG', 'Jungle')], max_length=3)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EUW', 'Europe West'), ('EUNE', 'Europe Nordic and East'), ('LAN', 'Latin America North'), ('LAS', 'Latin America South'), ('BR', 'Brazil'), ('JP', 'Japan'), ('RU', 'Russia'), ('TR', 'Turkey'), ('OCE', 'Oceana'), ('KR', 'Korea')], default='NORTH_AMERICA', max_length=2)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='league.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('profileIconId', models.IntegerField()),
                ('revisionDate', models.BigIntegerField()),
                ('summonerLevel', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.Summoner'),
        ),
    ]
