# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('champ_id', models.IntegerField(primary_key=True, serialize=False)),
                ('blurb', models.CharField(max_length=2000)),
                ('lore', models.CharField(max_length=4500)),
            ],
        ),
        migrations.AddField(
            model_name='allytip',
            name='champ_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allytips', to='league.Champion'),
        ),
    ]
