# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('champ_id', models.IntegerField()),
                ('blurb', models.CharField(max_length=2000)),
                ('lore', models.CharField(max_length=2000)),
                ('attack_rating', models.IntegerField()),
                ('defense_rating', models.IntegerField()),
                ('difficulty_rating', models.IntegerField()),
                ('magic_rating', models.IntegerField()),
                ('armor', models.FloatField()),
                ('armor_per_level', models.FloatField()),
                ('attack_damage', models.FloatField()),
                ('attack_damage_per_level', models.FloatField()),
                ('attack_range', models.FloatField()),
                ('attack_speed_offset', models.FloatField()),
                ('attack_speed_per_level', models.FloatField()),
                ('crit', models.FloatField()),
                ('crit_per_level', models.FloatField()),
                ('hp', models.FloatField()),
                ('hp_per_level', models.FloatField()),
                ('hp_regen', models.FloatField()),
                ('hp_regen_per_level', models.FloatField()),
                ('movespeed', models.FloatField()),
                ('mana', models.FloatField()),
                ('mana_per_level', models.FloatField()),
                ('mana_regen', models.FloatField()),
                ('mana_regen_per_level', models.FloatField()),
                ('spell_block', models.FloatField()),
                ('spell_block_per_level', models.FloatField()),
            ],
        ),
    ]
